import type { NextPage } from 'next'

import Head from 'next/head'
import React from 'react'

import styles from '../styles/Home.module.css'


export async function getServerSideProps() {
  const quotes = await fetch('http://localhost:3000/api/quotes')
  const data = await quotes.json()

  if (!data) {
    return {
      notFound: true,
    }
  }

  return {
    props: {data}, // will be passed to the page component as props
  }
}

const Home: NextPage = ({data}) => {
  console.log(data, 'llego')
  return (
    <div className={styles.container}>
      <Head>
        <title>Web Scrapper 2021</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  )
}



export default Home
